// Mocks generated by Mockito 5.1.0 from annotations
// in dima21_migliore_tortorelli/test/pages/categories_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:dima21_migliore_tortorelli/models/CategoryModel.dart' as _i5;
import 'package:dima21_migliore_tortorelli/models/ProductModel.dart' as _i6;
import 'package:dima21_migliore_tortorelli/providers/authentication.dart'
    as _i3;
import 'package:dima21_migliore_tortorelli/providers/data.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFirebaseFirestore_0 extends _i1.Fake
    implements _i2.FirebaseFirestore {}

class _FakeAuthenticationProvider_1 extends _i1.Fake
    implements _i3.AuthenticationProvider {}

/// A class which mocks [DataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataProvider extends _i1.Mock implements _i4.DataProvider {
  @override
  String get lastMessage =>
      (super.noSuchMethod(Invocation.getter(#lastMessage), returnValue: '')
          as String);
  @override
  set lastMessage(String? _lastMessage) =>
      super.noSuchMethod(Invocation.setter(#lastMessage, _lastMessage),
          returnValueForMissingStub: null);
  @override
  Map<String, _i5.CategoryModel> get categories =>
      (super.noSuchMethod(Invocation.getter(#categories),
              returnValue: <String, _i5.CategoryModel>{})
          as Map<String, _i5.CategoryModel>);
  @override
  Map<String, List<_i6.ProductModel>> get productsByCategories =>
      (super.noSuchMethod(Invocation.getter(#productsByCategories),
              returnValue: <String, List<_i6.ProductModel>>{})
          as Map<String, List<_i6.ProductModel>>);
  @override
  set selectedCategory(String? _selectedCategory) => super.noSuchMethod(
      Invocation.setter(#selectedCategory, _selectedCategory),
      returnValueForMissingStub: null);
  @override
  _i2.FirebaseFirestore get fireStore =>
      (super.noSuchMethod(Invocation.getter(#fireStore),
          returnValue: _FakeFirebaseFirestore_0()) as _i2.FirebaseFirestore);
  @override
  _i3.AuthenticationProvider get authenticationProvider =>
      (super.noSuchMethod(Invocation.getter(#authenticationProvider),
              returnValue: _FakeAuthenticationProvider_1())
          as _i3.AuthenticationProvider);
  @override
  set authenticationProvider(
          _i3.AuthenticationProvider? _authenticationProvider) =>
      super.noSuchMethod(
          Invocation.setter(#authenticationProvider, _authenticationProvider),
          returnValueForMissingStub: null);
  @override
  set productsUpdatesStreamSub(
          _i7.StreamSubscription<dynamic>? _productsUpdatesStreamSub) =>
      super.noSuchMethod(
          Invocation.setter(
              #productsUpdatesStreamSub, _productsUpdatesStreamSub),
          returnValueForMissingStub: null);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void update({_i3.AuthenticationProvider? authenticationProvider}) =>
      super.noSuchMethod(
          Invocation.method(
              #update, [], {#authenticationProvider: authenticationProvider}),
          returnValueForMissingStub: null);
  @override
  _i7.Future<bool> getAllCategories() =>
      (super.noSuchMethod(Invocation.method(#getAllCategories, []),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<bool> getProductsByCategory(String? categoryId,
          {bool? force = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getProductsByCategory, [categoryId], {#force: force}),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  void selectCategory(String? categoryId) =>
      super.noSuchMethod(Invocation.method(#selectCategory, [categoryId]),
          returnValueForMissingStub: null);
  @override
  void deselectCategory() =>
      super.noSuchMethod(Invocation.method(#deselectCategory, []),
          returnValueForMissingStub: null);
  @override
  void addListener(_i8.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i8.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
