// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:52498918263:android:eb31c6162dd129afd9cf72',
    messagingSenderId: '52498918263',
    projectId: 'optishop-88f04',
    storageBucket: 'optishop-88f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:52498918263:ios:930390409f80800ad9cf72',
    messagingSenderId: '52498918263',
    projectId: 'optishop-88f04',
    storageBucket: 'optishop-88f04.appspot.com',
    iosClientId: '52498918263-kha0t68oiaan6t6prau62i45nj3m47qp.apps.googleusercontent.com',
    iosBundleId: 'polimi.DIMA.dima21MiglioreTortorelli',
  );
}
