// Mocks generated by Mockito 5.2.0 from annotations
// in dima21_migliore_tortorelli/test/widget/home_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:dima21_migliore_tortorelli/models/CategoryModel.dart' as _i7;
import 'package:dima21_migliore_tortorelli/models/ProductModel.dart' as _i6;
import 'package:dima21_migliore_tortorelli/providers/authentication.dart'
    as _i4;
import 'package:dima21_migliore_tortorelli/providers/data.dart' as _i5;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFirebaseFirestore_0 extends _i1.Fake
    implements _i2.FirebaseFirestore {}

class _FakeFirebaseStorage_1 extends _i1.Fake implements _i3.FirebaseStorage {}

class _FakeAuthenticationProvider_2 extends _i1.Fake
    implements _i4.AuthenticationProvider {}

/// A class which mocks [DataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataProvider extends _i1.Mock implements _i5.DataProvider {
  @override
  String get lastMessage =>
      (super.noSuchMethod(Invocation.getter(#lastMessage), returnValue: '')
          as String);
  @override
  set lastMessage(String? _lastMessage) =>
      super.noSuchMethod(Invocation.setter(#lastMessage, _lastMessage),
          returnValueForMissingStub: null);
  @override
  Map<String, _i6.ProductModel> get loadedProducts =>
      (super.noSuchMethod(Invocation.getter(#loadedProducts),
              returnValue: <String, _i6.ProductModel>{})
          as Map<String, _i6.ProductModel>);
  @override
  Map<String, _i7.CategoryModel> get loadedCategories =>
      (super.noSuchMethod(Invocation.getter(#loadedCategories),
              returnValue: <String, _i7.CategoryModel>{})
          as Map<String, _i7.CategoryModel>);
  @override
  Map<String, List<String>?> get productsByCategory => (super.noSuchMethod(
      Invocation.getter(#productsByCategory),
      returnValue: <String, List<String>?>{}) as Map<String, List<String>?>);
  @override
  _i2.FirebaseFirestore get fireStore =>
      (super.noSuchMethod(Invocation.getter(#fireStore),
          returnValue: _FakeFirebaseFirestore_0()) as _i2.FirebaseFirestore);
  @override
  _i3.FirebaseStorage get firebaseStorage =>
      (super.noSuchMethod(Invocation.getter(#firebaseStorage),
          returnValue: _FakeFirebaseStorage_1()) as _i3.FirebaseStorage);
  @override
  _i4.AuthenticationProvider get authenticationProvider =>
      (super.noSuchMethod(Invocation.getter(#authenticationProvider),
              returnValue: _FakeAuthenticationProvider_2())
          as _i4.AuthenticationProvider);
  @override
  set authenticationProvider(
          _i4.AuthenticationProvider? _authenticationProvider) =>
      super.noSuchMethod(
          Invocation.setter(#authenticationProvider, _authenticationProvider),
          returnValueForMissingStub: null);
  @override
  set productsUpdatesStreamSub(
          _i8.StreamSubscription<dynamic>? _productsUpdatesStreamSub) =>
      super.noSuchMethod(
          Invocation.setter(
              #productsUpdatesStreamSub, _productsUpdatesStreamSub),
          returnValueForMissingStub: null);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void update({_i4.AuthenticationProvider? authenticationProvider}) =>
      super.noSuchMethod(
          Invocation.method(
              #update, [], {#authenticationProvider: authenticationProvider}),
          returnValueForMissingStub: null);
  @override
  _i8.Future<bool> getAllCategories() =>
      (super.noSuchMethod(Invocation.method(#getAllCategories, []),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<bool> getProductsByCategory(String? categoryId,
          {bool? force = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getProductsByCategory, [categoryId], {#force: force}),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<bool> getProduct(String? productId) =>
      (super.noSuchMethod(Invocation.method(#getProduct, [productId]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<String?> getProductByEAN(String? ean) =>
      (super.noSuchMethod(Invocation.method(#getProductByEAN, [ean]),
          returnValue: Future<String?>.value()) as _i8.Future<String?>);
  @override
  void addListener(_i9.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i9.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
